import java.io.*;
import java.util.Arrays;
import java.util.List;

public class prevEmployeeDatabase {
    File file;


    public prevEmployeeDatabase() {
        file = new File("prevEmployee_Info.txt");
        generateDataFile();
    }

    /**
     * This method generates a file to store employees and their attributes.
     * starts first line of the file with names of each categories.
     */
    public void generateDataFile(){
        if(!file.exists()){
            try {
                file.createNewFile();
                FileWriter fw = new FileWriter(file, true);
                PrintWriter pw = new PrintWriter(fw);
                pw.println("NAME, ID, DEPARTMENT, SALARY, DOB, HIRE_DATE, END_DATE,  STATUS");
                pw.close();
                fw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * write s in the file
     * @param s - a employee's info being added to the file generated by generateDataFile()
     */
    public void write(String s){
        if(file.exists()){
            try {
                FileWriter fw = new FileWriter(file, true);
                PrintWriter pw = new PrintWriter(fw);
                pw.println(s);
                pw.close();
                fw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * write employee e's data in the file using write(String s)
     * @param e - employee being added to the list of employee data
     */
    public void addEmployee(Employee e, String stat, String reas, String date) throws IOException {

        if(getEmployee(e.getID()) == null) {
            String employeeRecord;

            String name = e.getEmployeeName();
            String department = e.getDepartment();
            String DOB = e.getDOB();
            String hireDate = e.getHireDate();
            int ID = e.getID();
            int salary = e.getSalary();
            String status = stat;
            String reason = reas;
            String endDate = date;

            employeeRecord = name + ", " + ID + ", " + department + ", " + salary + ", " + DOB + ", " + hireDate + ", " + endDate + ", " + status;

            write(employeeRecord);
            write(reason);
        }

    }

    /**
     * remove employee e's data from the file
     * @param e - employee being deleted from the list of employee data
     * @throws IOException
     */
    public void removeEmployee(Employee e) throws IOException {
        File inputFile = new File("prevEmployee_Info.txt");
        File tempFile = new File("myTempFile.txt");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

        String strID = Integer.toString(e.getID());
        int skipLine = 0;

        String currentLine;

        while((currentLine = reader.readLine()) != null) {
        	
        	List<String> employeeInfo = Arrays.asList(currentLine.split("\\s*,\\s*"));
            if (employeeInfo.contains(strID))
            {
            	skipLine = 2;
            }
            if(skipLine <= 0)
            {
            	writer.write(currentLine + System.getProperty("line.separator"));
            }
            else
            {
            	skipLine--;
            }
             
            // trim newline when comparing with lineToRemove
            //String trimmedLine = currentLine.trim();
            //if(trimmedLine.equals(employeeRecord)) continue;
            //writer.write(currentLine + System.getProperty("line.separator"));
        }
        writer.close();
        reader.close();
        
        inputFile.delete();
        tempFile.renameTo(inputFile);
    }

    /**
     * get a instance of employee that has same ID with given parameter id
     * @param id
     * @return employee with same ID given
     * @throws IOException
     */
    public Employee getEmployee(int id) throws IOException {
        File inputFile = new File("prevEmployee_Info.txt");
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));

        Employee emp;

        String department, DOB, hireDate, name;
        int ID, salary;


        String currentLine;
        String strID = Integer.toString(id);

        while((currentLine = reader.readLine()) != null) {
            // trim newline when comparing with lineToRemove
            List<String> employeeInfo = Arrays.asList(currentLine.split("\\s*,\\s*"));
            if(employeeInfo.contains(strID)){
                department = employeeInfo.get(2);
                DOB = employeeInfo.get(4);
                hireDate = employeeInfo.get(5);
                name = employeeInfo.get(0);
                ID = Integer.parseInt(employeeInfo.get(1));
                salary = Integer.parseInt(employeeInfo.get(3));
                
                emp = new Employee(department, DOB, hireDate, name, ID, salary, 0);

                reader.close();
                
                return emp;
            }
        }
        reader.close();

        return null;
    }

    /**
     * This method prints employee information
     * @param id
     * @throws IOException
     */
    public void printEmployeeInfo(int id) throws IOException {
        File inputFile = new File("prevEmployee_Info.txt");
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));

        int getNextLine = 0;
        String currentLine;
        String strID = Integer.toString(id);
        System.out.println("NAME, ID, DEPARTMENT, SALARY, DOB, HIRE_DATE, END_DATE, STATUS");
        while((currentLine = reader.readLine()) != null) {
            List<String> employeeInfo = Arrays.asList(currentLine.split("\\s*,\\s*"));
            if(employeeInfo.get(1).equals(strID) || getNextLine == 1){
                System.out.println(currentLine);
                if(getNextLine == 1)
                {
                	getNextLine = 0;
                }
                else
                {
                	getNextLine = 1;
                }
            }

        }
        reader.close();
    }
    
    public void viewPrevEmployees() throws IOException
    {
        File inputFile = new File("prevEmployee_Info.txt");
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));

        while(reader.ready())
        {
            System.out.println(reader.readLine());
        }

        reader.close();
    }
}