import java.io.*;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class SystemProgram {
    employeeDatabase empDB;
    File file;

    /**
     * System Program Constructor
     */
    public SystemProgram(){
        file = new File("Employee_LogIn.txt");
        empDB = new employeeDatabase();
        generateDataFile();
    }

    /**
     * Run method runs entire program, nothing else needed to execute program
     * @throws IOException
     */
    public void run() throws IOException {
        boolean logInSuccess = false;

        while(!logInSuccess){
            logInSuccess = LogIn();
        }
    }

    /**
     * This method generates a file to store employees and their attributes.
     * starts first line of the file with names of each categories.
     */
    public void generateDataFile(){
        if(!file.exists()){
            try {
                file.createNewFile();
                FileWriter fw = new FileWriter(file, true);
                PrintWriter pw = new PrintWriter(fw);
                pw.println("EMPLOYEE ID, PASSWORD");
                pw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * Log in method for system
     * @return
     * @throws IOException
     */
    public boolean LogIn() throws IOException {
        Scanner input = new Scanner(System.in);

        System.out.println("Enter employee ID: ");
        String strEmployeeID = input.nextLine();
        int employeeID = Integer.valueOf(strEmployeeID);

        System.out.println("Enter password:");
        String password = input.nextLine();

        File inputFile = new File("Employee_LogIn.txt");
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));

        String currentLine;

        while((currentLine = reader.readLine()) != null) {
            // trim newline when comparing with lineToRemove
            List<String> employeeInfo = Arrays.asList(currentLine.split("\\s*,\\s*"));
            if(employeeInfo.get(0).equals(strEmployeeID) && employeeInfo.get(1).equals(password)){
                //create employee instance
                Employee e = empDB.getEmployee(employeeID);
                System.out.println("Logged in as " + e.getEmployeeName());
                e.doAction();
                return true;
            }
        }
        reader.close();

        System.out.println("Entered invalid employee ID or password.");

        return false;
    }

    /**
     * Changing password for user
     * @param id
     * @param password
     * @throws IOException
     */
    public void changePassword(int id, String password) throws IOException {
        File inputFile = new File("Employee_LogIn.txt");
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));

        String currentLine;

        while((currentLine = reader.readLine()) != null) {
            // trim newline when comparing with lineToRemove
            List<String> employeeInfo = Arrays.asList(currentLine.split("\\s*,\\s*"));
            if(employeeInfo.get(0).equals(id)){
                Employee e= empDB.getEmployee(id);
                empDB.removeEmployee(e);
                empDB.addEmployee(e);
            }

        }
        String entry = id+", "+ password;
        write(entry);
    }

    /**
     * write s in the file
     * @param s - a employee's info being added to the file generated by generateDataFile()
     */
    public void write(String s){
        if(file.exists()){
            try {
                FileWriter fw = new FileWriter(file, true);
                PrintWriter pw = new PrintWriter(fw);
                pw.println(s);
                pw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
